import type { RelatedLink } from "../types";

export const arHrefLabels: Record<string, string> = {
  "/services/event-management-oman": "إدارة الفعاليات",
  "/services/event-planning-oman": "تخطيط الفعاليات",
  "/services/event-production-oman": "إنتاج الفعاليات",
  "/services/corporate-events-oman": "الفعاليات المؤسسية",
  "/services/conference-management-oman": "إدارة المؤتمرات",
  "/services/exhibition-management-oman": "إدارة المعارض",
  "/services/exhibition-stand-design-oman": "تصميم الأجنحة",
  "/services/exhibition-stand-construction-oman": "تنفيذ الأجنحة",
  "/services/product-launches-oman": "إطلاق المنتجات",
  "/services/brand-activations-oman": "تفعيلات العلامة",
  "/services/gala-dinners-oman": "حفلات العشاء الرسمية",
  "/services/award-ceremonies-oman": "حفلات التكريم",
  "/services/government-events-oman": "الفعاليات الحكومية",
  "/services/vip-luxury-events-oman": "فعاليات كبار الشخصيات",
  "/services/weddings-oman": "الأعراس",
  "/services/destination-events-oman": "فعاليات الوجهات",
  "/services/roadshows-oman": "الجولات الميدانية",
  "/services/event-staffing-oman": "فريق الفعالية",
  "/services/registration-guest-management-oman": "التسجيل واستقبال الضيوف",
  "/services/audio-visual-oman": "الصوتيات والمرئيات",
  "/services/stage-design-oman": "تصميم المنصة",
  "/services/lighting-sound-oman": "الإضاءة والصوت",
  "/services/led-screens-oman": "شاشات LED",
  "/services/event-branding-oman": "هوية الفعالية",
  "/services/event-signage-oman": "إرشاد الفعالية",
  "/services/photography-videography-oman": "التصوير والفيديو",
  "/services/venue-logistics-oman": "تنسيق المكان واللوجستيات",
  "/services/traditional-omani-hospitality": "الضيافة العُمانية",
  "/services/omani-majlis-experiences": "تجارب المجلس",
  "/services/frankincense-welcome-rituals": "ترحيب اللبان",
  "/services/omani-folk-performance": "الأداء الشعبي العُماني",
  "/services/dhofar-cultural-programming": "البرامج الثقافية في ظفار",
  "/services/live-entertainment-oman": "الترفيه الحي",
  "/services/cultural-festivals-oman": "المهرجانات والبرامج الثقافية",
  "/industries/government-public-sector": "القطاع الحكومي",
  "/industries/corporate": "القطاع المؤسسي",
  "/industries/banking-finance": "البنوك والتمويل",
  "/industries/oil-gas-energy": "النفط والغاز والطاقة",
  "/industries/construction-real-estate": "الإنشاءات والعقارات",
  "/industries/hospitality-tourism": "الضيافة والسياحة",
  "/industries/healthcare": "الرعاية الصحية",
  "/industries/education": "التعليم",
  "/industries/technology-telecom": "التقنية والاتصالات",
  "/industries/automotive": "السيارات",
  "/industries/maritime-logistics": "الموانئ واللوجستيات",
  "/industries/luxury-retail": "الفخامة والتجزئة",
  "/industries/sports-entertainment": "الرياضة والترفيه",
  "/industries/manufacturing": "التصنيع",
  "/locations/muscat": "مسقط",
  "/locations/salalah": "صلالة",
  "/locations/sohar": "صحار",
  "/locations/nizwa": "نزوى",
  "/locations/sur": "صور",
  "/locations/duqm": "الدقم",
  "/locations/khasab": "خصب",
};

export function arLinks(links: RelatedLink[]): RelatedLink[] {
  return links.map((item) => ({ ...item, label: arHrefLabels[item.href] ?? item.label }));
}
