import type { ArticleDoc } from "./types";

export const articles: ArticleDoc[] = [
  {
    slug: "corporate-event-planning-oman",
    title: "How to Plan a Corporate Event in Oman",
    h1: "A working timeline for corporate events in Oman",
    description: "How communications teams in Oman should sequence venue holds, bilingual materials, hospitality and production for a corporate day.",
    date: "2026-09-10",
    category: "Planning",
    lede: "Corporate events in Oman stall when the hotel is held late, the agenda ignores prayer and traffic, or English-only decks meet a mixed room. This timeline is written for Muscat-centred programmes that may still travel.",
    sections: [
      { heading: "Ninety days out", paragraphs: ["Lock the outcome: decision, launch, recognition, or internal alignment. Then hold the room. Muscat winter and National Day-adjacent dates fill hotel ballrooms faster than a spreadsheet suggests.", "Name a single internal owner. Vendors cannot share a brain. Vulture Events Oman works as an external producer; we still need one person inside the company who can decide."] },
      { heading: "The bilingual problem", paragraphs: ["If any official names, ministerial guests or Omani staff leadership will be in the room, design Arabic and English together. Last-minute translation on slides is how titles go wrong.", "Hosting language at the door should match the guest list, not the HQ’s default."] },
      { heading: "Show week", paragraphs: ["Rehearse speeches and playback. Walk the registration line. Confirm banquet timing so plates do not compete with the CEO.", "If a second city is involved, freight should already be on the road. Same-morning heroics between Muscat and Sohar are a common failure."] },
    ],
    relatedServices: [{ href: "/services/corporate-events-oman", label: "Corporate events" }, { href: "/services/event-planning-oman", label: "Event planning" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "conference-planning-muscat-ocec",
    title: "Conference Planning in Muscat and at OCEC",
    h1: "Choosing between OCEC-scale halls and hotel congresses in Muscat",
    description: "How to decide whether a Muscat conference belongs at Oman Convention & Exhibition Centre or in a hotel, and what each choice changes operationally.",
    date: "2026-09-08",
    category: "Conferences",
    lede: "Muscat has two honest conference geographies: convention-centre scale at Madinat Al Irfan, and hotel ballrooms that behave like large meeting rooms. They are not interchangeable.",
    sections: [
      { heading: "When OCEC-scale is the right class", paragraphs: ["If you need exhibition plus plenary plus organiser offices, a convention-centre hall plan is usually cleaner. Dividable halls, registration volume and dock access are the reasons — not prestige.", "Work to the venue’s operating rules. We discuss OCEC as a venue class, not as an exclusive partnership."] },
      { heading: "When a hotel is enough", paragraphs: ["Single-room corporate days, dinners the same evening, and guest-room adjacency often belong in a hotel. The trade-off is tighter hanging points, neighbour noise and banquet service colliding with sessions.", "Al Bustan-class ballrooms and Qurum or Al Mouj hotels are different rooms. Recce before you draw a stage."] },
      { heading: "Delegate circulation", paragraphs: ["The conference dies in the coffee break if toilets, prayer space and exhibition aisles are an afterthought. Draw the walk.", "Interpretation booths and recording need space that is not a leftover corridor."] },
    ],
    relatedServices: [{ href: "/services/conference-management-oman", label: "Conference management" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "event-production-oman",
    title: "Event Production in Oman",
    h1: "What event production actually includes on an Oman show",
    description: "A plain-language explanation of staging, power, crew, rehearsal and show-calling for events in Oman.",
    date: "2026-09-06",
    category: "Production",
    lede: "Production is the live machine: power, scenic, lighting, sound, LED, comms and a caller. Planning documents without this layer are essays.",
    sections: [
      { heading: "Start with the room, not the render", paragraphs: ["Hotel engineering in Muscat will tell you what you may hang. Gardens in Salalah will tell you what humidity does to paper and LED. Plant sites will tell you about induction. Listen before you design.", "A travelling kit for Duqm is not a capital ballroom wall in a smaller crate. Design the tour to the smallest honest room."] },
      { heading: "Rehearsal is not optional", paragraphs: ["Speeches, interpretation, reveals and content all need cue-to-cue. If it cannot be rehearsed, simplify it.", "The caller owns the clock. Banquet, security and hosts take cues from the same sheet."] },
    ],
    relatedServices: [{ href: "/services/event-production-oman", label: "Event production" }, { href: "/services/audio-visual-oman", label: "Audio visual" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }, { href: "/locations/duqm", label: "Duqm" }],
  },
  {
    slug: "ramadan-corporate-events-oman",
    title: "Corporate Ramadan Events in Oman",
    h1: "Planning corporate hospitality during Ramadan in Oman",
    description: "How to time, staff and host corporate gatherings in Oman during Ramadan without forcing a daytime template into iftar hours.",
    date: "2026-08-28",
    category: "Seasonal",
    lede: "Ramadan changes the working day, the meal, and the tone. Copying a March town-hall timetable into fasting hours is how programmes feel careless.",
    sections: [
      { heading: "Time is the design", paragraphs: ["Iftar-related programmes need a clock that respects sunset, traffic and family obligations. Do not stack workshops until 18:00 and hope.", "Non-fasting crew still need a discreet plan for water and rest that does not perform itself in front of guests."] },
      { heading: "Hospitality tone", paragraphs: ["Welcome rituals can be quieter. Entertainment should not fight the room. Kahwa and dates may belong; a loud activation probably does not.", "Confirm photography rules. Many hosts prefer fewer cameras during this period."] },
      { heading: "Eid is a different brief", paragraphs: ["Eid gatherings are not a leftover Ramadan template. Family flow, hotel inventory and a more celebratory tone need their own clock.", "If the same host wants both an iftar week and an Eid reception, treat them as two programmes that share a producer, not as one recycled run of show."] },
    ],
    relatedServices: [{ href: "/services/corporate-events-oman", label: "Corporate events" }, { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "oman-national-day-event-planning",
    title: "Oman National Day Event Planning",
    h1: "National Day-adjacent programmes: flags, performance and protocol",
    description: "How to plan Oman National Day related events with correct marks, Omani performance and a ceremony clock.",
    date: "2026-08-20",
    category: "Official",
    lede: "18 November and the days around it are not a colour palette. They are official marks, diaries and a public mood. Production should be exact.",
    sections: [
      { heading: "Marks and language", paragraphs: ["Use authorised artwork. Bilingual titles need proofing. Do not invent ceremonial slogans.", "If the programme is private-corporate rather than official, still treat flags and anthems with the same care."] },
      { heading: "Performance", paragraphs: ["Source Omani forms such as Razha or Al-Azi from troupes who work in them. Do not substitute a generic regional act.", "Give the piece space and an ending, then continue the evening."] },
    ],
    relatedServices: [{ href: "/services/government-events-oman", label: "Government events" }, { href: "/services/omani-folk-performance", label: "Omani folk performance" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "khareef-salalah-event-planning",
    title: "Planning Events During Khareef in Salalah",
    h1: "Khareef is a production season, not only a landscape",
    description: "How humidity, hotel inventory, freight from Muscat and outdoor risk change event production in Salalah during Khareef.",
    date: "2026-08-12",
    category: "Seasonal",
    lede: "Khareef fills Dhofar with guests and mist. It also fills hotels, delays outdoor looks, and punishes kits that were specified for dry Muscat air.",
    sections: [
      { heading: "Hold early", paragraphs: ["Rooms and flights disappear. A Muscat-style four-week hold is often theatre.", "Banquet halls still need indoor plots even if the terrace is the hero image."] },
      { heading: "Moisture and freight", paragraphs: ["Paper, fabrics, makeup and some LED behaviour change. Spec covers and indoor twins for every garden cue.", "Freight from Muscat is a calendar item. Local cultural programming should be sourced in Dhofar, not imported as a costume box."] },
    ],
    relatedServices: [{ href: "/services/dhofar-cultural-programming", label: "Dhofar programming" }, { href: "/services/destination-events-oman", label: "Destination events" }],
    relatedLocations: [{ href: "/locations/salalah", label: "Salalah" }],
  },
  {
    slug: "muscat-event-venues",
    title: "Event Venue Selection in Muscat",
    h1: "How to shortlist event venues in Muscat without a scraped directory",
    description: "A method for choosing Muscat event venues by guest count, technical limits, guest geography and adjacency — not by a list of logos.",
    date: "2026-08-05",
    category: "Venues",
    lede: "Muscat venue choice is a matching problem: count, power, docks, guest hotels and the tone of the organisation. Directories without those filters waste weeks.",
    sections: [
      { heading: "Ask operational questions first", paragraphs: ["What can you hang? When is load-in? Where do trucks wait? How does the coastal road behave at that hour?", "Qurum, Al Mouj, Muttrah overlays, Seeb airport-side and Madinat Al Irfan are different guest geographies."] },
      { heading: "Do not collect exclusives", paragraphs: ["We name venue classes such as OCEC-scale halls and Al Bustan-class ballrooms because they exist. We do not claim they are ours.", "A recce beats a brochure. Glass walls fight LED. Gardens fight wind."] },
    ],
    relatedServices: [{ href: "/services/venue-logistics-oman", label: "Venue logistics" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "exhibition-planning-oman",
    title: "Exhibition Planning in Oman",
    h1: "Exhibition planning: aisles, power and a stand that can be staffed",
    description: "How exhibitors and organisers should plan Oman exhibitions, from floorplans to bilingual graphics and freight.",
    date: "2026-07-30",
    category: "Exhibitions",
    lede: "Shows in Oman are won in the aisle. If fire lanes, power and graphics hierarchy are wrong, the render does not matter.",
    sections: [
      { heading: "Organiser versus exhibitor jobs", paragraphs: ["Hall management and stand building are different scopes. Mixing them in one vague fee is how both jobs get thinner.", "Exhibitor kits should tell the truth about build windows."] },
      { heading: "Design that crates", paragraphs: ["A Muscat island may not travel to Salalah. If the brief is a roadshow, design the crate first.", "Arabic and English on the fascia need a hierarchy, not two competing headlines."] },
    ],
    relatedServices: [{ href: "/services/exhibition-stand-design-oman", label: "Stand design" }, { href: "/services/exhibition-management-oman", label: "Exhibition management" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "vip-protocol-events-oman",
    title: "VIP Event Planning in Oman",
    h1: "VIP protocol as production: cars, names and quiet staff",
    description: "How to plan VIP events in Oman with arrival order, seating honour, photography limits and discreet crew.",
    date: "2026-07-22",
    category: "VIP",
    lede: "VIP work is mostly traffic, names and restraint. Flowers are the easy part.",
    sections: [
      { heading: "Write the honour order", paragraphs: ["Who is greeted first, who sits where, who may be photographed. If the host cannot answer, the event is not ready.", "Holding rooms need chairs, water, and a clock — not a leftover closet."] },
      { heading: "Staffing", paragraphs: ["Fewer people, better briefed. Ushers who perform enthusiasm in a protocol line are a liability.", "Devices and social posting default to no unless the host says yes."] },
    ],
    relatedServices: [{ href: "/services/vip-luxury-events-oman", label: "VIP events" }, { href: "/services/government-events-oman", label: "Government events" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "destination-events-oman",
    title: "Luxury Destination Events in Oman",
    h1: "Destination events that still start on time",
    description: "How to build destination programmes in Oman using landscape as a chapter — Hajar, coast, Dhofar, Musandam — without becoming a tour desk.",
    date: "2026-07-15",
    category: "Destination",
    lede: "Oman’s landscape is a gift that ruins programmes when transfers eat the day. Treat every move as a cue.",
    sections: [
      { heading: "Protect the working room", paragraphs: ["Leadership still needs a table that works. Do not replace the meeting with a viewpoint.", "Nizwa, Salalah and Khasab are different operating pictures. Do not stack all three."] },
      { heading: "Weather twins", paragraphs: ["Every outdoor cue needs an indoor version. Sea state in Musandam and mist in Khareef are not surprises.", "Hospitality should feel Omani without becoming costume."] },
    ],
    relatedServices: [{ href: "/services/destination-events-oman", label: "Destination events" }],
    relatedLocations: [{ href: "/locations/nizwa", label: "Nizwa" }, { href: "/locations/khasab", label: "Khasab" }, { href: "/locations/salalah", label: "Salalah" }],
  },
  {
    slug: "government-event-planning-oman",
    title: "Government Event Planning in Oman",
    h1: "Public-sector programmes: the protocol pack is the brief",
    description: "A practical approach to government event planning in Oman, from bilingual titles to media positions and discreet crew.",
    date: "2026-07-08",
    category: "Official",
    lede: "Government events are judged on order. Production that tries to ‘energise’ a ceremony usually fails.",
    sections: [
      { heading: "Start with the pack", paragraphs: ["Names, languages, arrival, what may be filmed. Scenic follows. Not the reverse.", "Crew presence should be competent and quiet. Headsets are not a fashion item in the front row."] },
      { heading: "Governorate delivery", paragraphs: ["A capital-quality cue sheet still has to travel. Freight and local permissions are part of respect, not bureaucracy for its own sake."] },
    ],
    relatedServices: [{ href: "/services/government-events-oman", label: "Government events" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }, { href: "/locations/duqm", label: "Duqm" }],
  },
  {
    slug: "oman-event-production-checklist",
    title: "Oman Event Production Checklist",
    h1: "An operational checklist before you lock an Oman event",
    description: "A practical production checklist for events in Oman covering venue, power, languages, freight, rehearsal and teardown.",
    date: "2026-07-01",
    category: "Production",
    lede: "Use this as a conversation, not a talisman. If a line is blank a week out, that is the risk.",
    sections: [
      { heading: "Room and power", paragraphs: ["Recce notes, hanging points, dock times, generator need, house AV truthfulness.", "Outdoor: wind, dew, heat, shade, neighbour noise."] },
      { heading: "People and language", paragraphs: ["Bilingual materials proofed. Host language mix. Interpretation tested. Protocol names locked.", "Crew housing if not Muscat. Overnight labour named."] },
      { heading: "Show and after", paragraphs: ["Cue sheet owners. Rehearsal block. Content backups. Teardown and crate list.", "Photography consent. Data from registration handled to policy."] },
    ],
    relatedServices: [{ href: "/services/event-production-oman", label: "Event production" }, { href: "/services/venue-logistics-oman", label: "Venue logistics" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "corporate-hospitality-majlis-oman",
    title: "Corporate Hospitality and Majlis Experiences in Oman",
    h1: "Using a majlis as a designed corporate welcome",
    description: "How corporate hosts in Oman can use majlis seating, kahwa and honour order as a guest system rather than decoration.",
    date: "2026-06-24",
    category: "Hospitality",
    lede: "A couple of couches beside a speaker tower is not a majlis. The room needs etiquette, acoustics and an ending.",
    sections: [
      { heading: "Architecture", paragraphs: ["Clusters, shade, scent, a path in and a path out. Hosts who know who sits where.", "Then move guests when the plenary requires it — with dignity, not a shout."] },
      { heading: "International guests", paragraphs: ["A light explanation from a host is enough. Do not lecture a room of engineers about heritage while the agenda slips."] },
    ],
    relatedServices: [{ href: "/services/omani-majlis-experiences", label: "Majlis experiences" }, { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "event-branding-oman",
    title: "Event Branding in Oman",
    h1: "Bilingual event branding that still looks like one organisation",
    description: "How to design event branding in Oman so Arabic and English share a hierarchy from kerb to stage.",
    date: "2026-06-18",
    category: "Branding",
    lede: "Guidelines written for A4 fail on a twelve-metre wall. Official names fail when they are translated in the taxi.",
    sections: [
      { heading: "Map surfaces, then edit", paragraphs: ["Arrival, desk, wayfinding, stage, table, badge, screen. If they disagree, guests notice.", "Not every surface needs a manifesto."] },
      { heading: "Language pair", paragraphs: ["Design Arabic and English together. Proof titles with the host. Protocol marks only when authorised."] },
    ],
    relatedServices: [{ href: "/services/event-branding-oman", label: "Event branding" }, { href: "/services/event-signage-oman", label: "Signage" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "audio-visual-production-oman-events",
    title: "Audio Visual Production for Oman Events",
    h1: "AV in Oman rooms: speech first, then the pretty parts",
    description: "How to specify audio visual production for Oman events, including interpretation, recording and LED versus projection.",
    date: "2026-06-10",
    category: "Production",
    lede: "If people cannot hear, the LED wall is a monument to the wrong problem.",
    sections: [
      { heading: "Measure the room", paragraphs: ["Ballrooms swallow speech. Glass fights projection. Sun fights LED. Recce beats catalogue pages.", "Interpretation is a designed feed. A shared handheld is not a conference solution."] },
      { heading: "Content ops", paragraphs: ["Someone must recover a failed clip. Backup players are cheaper than a stalled keynote.", "LED pitch follows viewing distance. More square metres is not automatically more premium."] },
    ],
    relatedServices: [{ href: "/services/audio-visual-oman", label: "Audio visual" }, { href: "/services/led-screens-oman", label: "LED screens" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "roadshow-logistics-oman",
    title: "Roadshow Logistics in Oman",
    h1: "Moving a show between Muscat, Sohar, Duqm and Salalah",
    description: "How to plan event roadshow logistics in Oman, including freight windows, crew rest and kits that fit the smallest room.",
    date: "2026-06-02",
    category: "Logistics",
    lede: "City three looks different when city one used a kit that cannot crate. Design the tour backwards from the smallest honest venue.",
    sections: [
      { heading: "The sequence", paragraphs: ["Industrial briefs often run Muscat then Sohar and/or Duqm. The south is a different calendar because of flights and Khareef.", "Rest is a line item. Tired crews make unsafe docks."] },
      { heading: "Consistency versus localisation", paragraphs: ["Brand messages stay still. Breakfast length and hospitality can change with the city.", "If a date cannot be freighted, change the date — not the laws of distance."] },
    ],
    relatedServices: [{ href: "/services/roadshows-oman", label: "Roadshows" }, { href: "/services/venue-logistics-oman", label: "Venue logistics" }],
    relatedLocations: [{ href: "/locations/sohar", label: "Sohar" }, { href: "/locations/duqm", label: "Duqm" }, { href: "/locations/salalah", label: "Salalah" }],
  },
  {
    slug: "arabic-english-event-support-oman",
    title: "Arabic and English Event Support in Oman",
    h1: "Bilingual events: interpretation, hosting and print that agree",
    description: "How to plan Arabic and English event support in Oman across hosting, signage, slides and simultaneous interpretation.",
    date: "2026-05-26",
    category: "Language",
    lede: "Mixed rooms are normal in Muscat. English-only production is a choice, not a default, and it shows.",
    sections: [
      { heading: "Three layers", paragraphs: ["Print and screens: designed as a pair. Hosting: staffed to the guest mix. Interpretation: a technical feed, rehearsed.", "Machine translation is not a guest-facing method."] },
      { heading: "Names", paragraphs: ["Honorifics and dual-script names need proofing time. Registration desks that improvise become protocol incidents."] },
    ],
    relatedServices: [{ href: "/services/event-staffing-oman", label: "Event staffing" }, { href: "/services/conference-management-oman", label: "Conference management" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
  {
    slug: "wedding-event-management-muscat",
    title: "Wedding Event Management in Muscat",
    h1: "Muscat weddings as produced days, not vendor piles",
    description: "How families in Muscat can use a producer to hold timing, hotel liaison and guest flow on a wedding day.",
    date: "2026-05-18",
    category: "Weddings",
    lede: "A Muscat hotel wedding has a clock: arrival, photographs, dinner, send-off. Without a caller, those chapters overlap and nobody eats.",
    sections: [
      { heading: "What a producer does", paragraphs: ["Liaise with the hotel, hold vendors to the timeline, run speeches and music so they do not collide, and keep family hosts free to be present.", "We do not replace the family. We keep the day standing."] },
      { heading: "Gardens and peak dates", paragraphs: ["Outdoor looks need weather twins. Peak hotels book early. Cultural elements should be the family’s, not a catalogue from elsewhere."] },
    ],
    relatedServices: [{ href: "/services/weddings-oman", label: "Weddings" }],
    relatedLocations: [{ href: "/locations/muscat", label: "Muscat" }],
  },
];

export function getArticle(slug: string) {
  return articles.find((item) => item.slug === slug);
}
