import type { ServiceDoc } from "./types";

const muscat = { href: "/locations/muscat", label: "Muscat" };
const salalah = { href: "/locations/salalah", label: "Salalah" };
const sohar = { href: "/locations/sohar", label: "Sohar" };
const duqm = { href: "/locations/duqm", label: "Duqm" };

export const services: ServiceDoc[] = [
  {
    slug: "event-management-oman",
    nav: "Event Management",
    group: "management",
    title: "Event Management Company in Oman",
    h1: "Event management with one producer accountable for Oman",
    description:
      "Full-service event management in Oman for conferences, ceremonies, exhibitions and guest programmes, operated from Muscat.",
    lede: "Event management here means owning the brief through teardown — venue, run of show, technical, staffing and hospitality — without splitting the room between uncoordinated vendors.",
    overview: [
      "Organisations in Oman brief us when a date is real and the outcome is public: a conference that must start on time, a ceremony that must honour names, an exhibition that must work on the floor. We appoint one producer who holds the timeline, the budget frame and the cue sheet.",
      "Muscat is the operating centre. When the programme moves to Salalah, Sohar, Duqm or another named city, freight and crew travel on the same document. We do not treat other governorates as an afterthought paragraph.",
    ],
    includes: ["Discovery and feasibility", "Venue coordination", "Run of show", "Vendor orchestration", "On-site show calling", "Teardown and wrap"],
    capabilities: ["Bilingual guest materials", "Protocol-aware seating", "Multi-city logistics", "Production and hospitality under one lead"],
    formats: ["Corporate days", "Official ceremonies", "Conferences", "Private celebrations"],
    oman: [
      "Hotel engineering rules in Muscat differ from OCEC hall rules and from a Salalah garden in Khareef. We recce or pull current venue packs before locking scenic.",
      "Arabic and English are designed together. English-only rooms still need accurate Arabic on official names when dignitaries are present.",
    ],
    approach: [
      "We write a production plan you can interrogate: assumptions, optional extras, and what happens if the guest count moves.",
      "Show day is run from the sheet. You host. We restore the room.",
    ],
    audience: "Corporate, government, agencies and private hosts who need a single Oman-based production lead.",
    faqs: [
      { q: "What does an event management company in Oman do?", a: "It turns a date, audience and outcome into a produced programme: venues, technical, staffing, hospitality and teardown, with one team accountable." },
      { q: "Do you only work in Muscat?", a: "Operations are centred in Muscat. Delivery follows the brief, including Salalah, Sohar, Nizwa, Sur, Duqm and Khasab." },
      { q: "How do we start?", a: "Send date, city, guests, event type and the services you think you need via the proposal form. We reply with questions if the brief is thin." },
    ],
    relatedServices: [
      { href: "/services/event-production-oman", label: "Event production" },
      { href: "/services/corporate-events-oman", label: "Corporate events" },
      { href: "/services/conference-management-oman", label: "Conference management" },
    ],
    relatedIndustries: [
      { href: "/industries/corporate", label: "Corporate" },
      { href: "/industries/government-public-sector", label: "Government" },
    ],
    relatedLocations: [muscat, salalah, sohar],
  },
  {
    slug: "event-planning-oman",
    nav: "Event Planning",
    group: "management",
    title: "Event Planning in Oman",
    h1: "Event planning that holds the calendar before the build begins",
    description:
      "Event planning in Oman covering agendas, vendor maps, guest journeys and run-of-show documents for Muscat and nationwide programmes.",
    lede: "Planning is the document layer: who does what, when the room turns, and how guests move. It is not the same job as fabricating a stand or hanging a truss.",
    overview: [
      "Some briefs need a planner to orchestrate existing hotel packages, internal AV and a small guest list. Others need planning as the first phase of a full production. We say which one you are buying.",
      "In Oman the calendar collides with Ramadan, National Day-adjacent dates, Khareef inventory and ministry diaries. Those collisions belong on the first Gantt chart.",
    ],
    includes: ["Workback schedules", "Vendor maps", "Guest journey drafts", "Agenda design", "Risk register", "Budget frames"],
    capabilities: ["Hotel liaison", "Bilingual agenda design", "Multi-stakeholder versions of the same plan"],
    formats: ["Internal conferences", "Dinners", "Workshops", "Hybrid hotel + HQ days"],
    oman: ["We plan around prayer times, traffic on the coastal road, and hotel load-in windows that are shorter than the creative team hopes."],
    approach: ["A planning engagement can stop at documents, or continue into production. The proposal states the boundary."],
    audience: "In-house comms teams who need structure, and organisations not yet ready to lock full production.",
    faqs: [
      { q: "Is planning separate from production?", a: "It can be. Planning owns documents and orchestration. Production owns technical delivery. Many clients retain both." },
      { q: "Can you plan an event we will staff ourselves?", a: "Yes. You receive a run of show and vendor map you can execute, with optional show-day support." },
      { q: "How early should planning start?", a: "As soon as the date is more than a wish. Venue holds in Muscat winter are the usual critical path." },
    ],
    relatedServices: [
      { href: "/services/event-management-oman", label: "Event management" },
      { href: "/services/registration-guest-management-oman", label: "Registration" },
    ],
    relatedIndustries: [{ href: "/industries/corporate", label: "Corporate" }],
    relatedLocations: [muscat],
  },
  {
    slug: "event-production-oman",
    nav: "Event Production",
    group: "production",
    title: "Event Production in Oman",
    h1: "Event production: cue-to-cue, power, crew and a calm show call",
    description:
      "Event production in Oman including staging, LED, lighting, sound, rehearsal and show-calling for Muscat venues and travelling programmes.",
    lede: "Production is the physical show. We spec the room you actually have, rehearse the cues, and put a named caller on comms.",
    overview: [
      "Oman rooms range from OCEC halls to hotel ballrooms with modest hanging points to gardens that look generous until the wind arrives. The plot starts with power, access and sightlines — not with a moodboard that ignores the ceiling.",
      "We crew the show: stage, content, lighting, sound and hospitality handovers. Rehearsal is not optional on programmes with speeches, interpretation or reveals.",
    ],
    includes: ["Technical recce", "Stage and scenic", "Lighting and sound plots", "LED and switching", "Rehearsal", "Show calling"],
    capabilities: ["Speech-first audio", "Interpretation feeds", "Content operations", "Touring kits for other governorates"],
    formats: ["Plenaries", "Galas", "Launches", "Ceremonies"],
    oman: ["Hotel union of engineering + in-house AV can constrain what we hang. We design inside those rules or we recommend a different room."],
    approach: ["A production rider and a cue sheet are delivered before show week. Changes after rehearsal are possible; chaos is not a method."],
    audience: "Clients with a programme that must actually run, not only look expensive in a rendering.",
    faqs: [
      { q: "What does event production include in Oman?", a: "Scenic, lighting, sound, LED, crew, rehearsal and a show-caller. Hospitality and planning may sit alongside, but production is the live machine." },
      { q: "Do you rent equipment?", a: "We specify and supply a technical package for the room. The proposal lists what is included versus venue house kit." },
      { q: "Can production travel to Salalah or Duqm?", a: "Yes, with earlier freight. Travelling shows get a tighter, more redundant kit." },
    ],
    relatedServices: [
      { href: "/services/audio-visual-oman", label: "Audio visual" },
      { href: "/services/led-screens-oman", label: "LED screens" },
      { href: "/services/stage-design-oman", label: "Stage design" },
    ],
    relatedIndustries: [
      { href: "/industries/technology-telecom", label: "Technology" },
      { href: "/industries/corporate", label: "Corporate" },
    ],
    relatedLocations: [muscat, salalah, duqm],
  },
  {
    slug: "corporate-events-oman",
    nav: "Corporate Events",
    group: "management",
    title: "Corporate Events in Oman",
    h1: "Corporate events that keep the working day intact",
    description:
      "Corporate event management in Oman for town halls, partner days, leadership offsites and internal conferences.",
    lede: "A corporate day in Muscat should feel like your organisation, not like a generic gala rented by the hour.",
    overview: [
      "Town halls, offsites and partner days fail when registration overruns and the first speaker starts late. We design arrival, coffee, sessions and the evening as one circulation, with bilingual titles where the audience is mixed.",
      "When the brief includes a plant visit or a second city, those chapters get the same cue discipline as the ballroom.",
    ],
    includes: ["Agenda architecture", "Room plans", "Technical for speeches", "Hospitality timing", "Content capture", "Show calling"],
    capabilities: ["HQ and hotel hybrids", "Confidential breakouts", "Ramadan-aware scheduling"],
    formats: ["Town halls", "Partner days", "Offsites", "Awards dinners"],
    oman: ["Many corporate audiences mix Omani nationals and expatriates. Hosting, humour and music choices are briefed, not improvised."],
    approach: ["We ask what must be true at 18:00: a decision, a feeling, a film, a handshake. The room is built backwards from that."],
    audience: "Comms, HR, CEOs’ offices and agencies booking Oman delivery.",
    faqs: [
      { q: "Can you produce a corporate event during Ramadan in Oman?", a: "Yes. Timing, hospitality and tone change. We plan iftar-aware schedules rather than shrinking a daytime template." },
      { q: "Do you work in headquarters auditoriums?", a: "Yes, with honest plots for rooms that were designed as offices first." },
      { q: "What guest counts are typical?", a: "From board dinners to hundreds in a hotel ballroom. Tell us the number; we will not upsell a congress kit to a 40-person room." },
    ],
    relatedServices: [
      { href: "/services/conference-management-oman", label: "Conference management" },
      { href: "/services/gala-dinners-oman", label: "Gala dinners" },
    ],
    relatedIndustries: [
      { href: "/industries/corporate", label: "Corporate" },
      { href: "/industries/banking-finance", label: "Banking" },
    ],
    relatedLocations: [muscat, sohar],
  },
  {
    slug: "conference-management-oman",
    nav: "Conference Management",
    group: "management",
    title: "Conference Management in Oman",
    h1: "Conference management for OCEC-scale and hotel congresses",
    description:
      "Conference management in Oman including delegate flow, faculty care, interpretation, exhibition overlay and technical cueing.",
    lede: "A conference is a city for two days. Registration, rooms, catering, exhibition and speakers have to share a clock.",
    overview: [
      "Muscat congresses often sit at Oman Convention & Exhibition Centre or in large hotels. The jobs differ: OCEC rewards clear hall plans and organiser offices; hotels reward tight turns and neighbour-noise diplomacy.",
      "We manage speaker care, session timing, bilingual wayfinding and the technical plot so a workshop in room three does not steal the plenary’s start.",
    ],
    includes: ["Delegate journey", "Faculty hospitality", "Room turns", "Interpretation coordination", "Exhibition overlay", "Recording"],
    capabilities: ["Multi-session grids", "Poster areas", "Sponsor circulation that does not block fire lanes"],
    formats: ["Association congresses", "Medical meetings", "Leadership summits", "Public forums"],
    oman: ["Simultaneous interpretation is common on regional programmes. We test feeds before doors, not during the keynote."],
    approach: ["The run of show is a grid, not a novel. Owners are named for every room."],
    audience: "Associations, corporates, healthcare organisers and public bodies hosting multi-session programmes.",
    faqs: [
      { q: "What does conference management include?", a: "Agenda logistics, registration design, room turns, faculty care, technical plots, exhibition overlay and a caller protecting start times." },
      { q: "Do you work at OCEC?", a: "Yes, as a venue class. We work to OCEC’s operating rules and do not claim an exclusive in-house role." },
      { q: "Can you handle poster sessions and workshops?", a: "Yes. Lighting, power and wayfinding for posters are specified, not left as leftover banquet tables." },
    ],
    relatedServices: [
      { href: "/services/registration-guest-management-oman", label: "Registration" },
      { href: "/services/audio-visual-oman", label: "Audio visual" },
      { href: "/services/exhibition-management-oman", label: "Exhibition management" },
    ],
    relatedIndustries: [
      { href: "/industries/healthcare", label: "Healthcare" },
      { href: "/industries/education", label: "Education" },
    ],
    relatedLocations: [muscat],
  },
  {
    slug: "exhibition-management-oman",
    nav: "Exhibition Management",
    group: "exhibitions",
    title: "Exhibition Management in Oman",
    h1: "Exhibition management that makes the floor usable",
    description:
      "Exhibition management in Oman for organisers and exhibitors, covering floorplans, exhibitor kits, build windows and on-site operations.",
    lede: "Exhibitions fail in the aisles: blocked fire lanes, late builds, graphics that cannot be read from ten metres. We manage the floor as an operation.",
    overview: [
      "Organisers need floorplans, kits, contractor control and a hall that opens on time. Exhibitors need a stand that can be staffed and a lead process that is not a fishbowl of laptops.",
      "Oman halls — especially OCEC-scale rooms — have their own build windows and power maps. We work to those, not to a foreign venue’s habits.",
    ],
    includes: ["Floorplanning", "Exhibitor communication", "Build supervision", "Aisle management", "Opening readiness", "Breakdown"],
    capabilities: ["Organiser-side hall management", "Exhibitor-side turnkey stands", "Graphics coordination"],
    formats: ["Trade exhibitions", "Congress expos", "Public showcases"],
    oman: ["Freight into Muscat and onwards to Salalah or Duqm needs earlier cut-offs than exhibitors from other markets expect."],
    approach: ["We publish a hall schedule and keep it. Late creative is cropped to fit the clock, not the other way around."],
    audience: "Show organisers, brands exhibiting in Oman, and agencies needing local floor operations.",
    faqs: [
      { q: "What is included in exhibition management?", a: "Floorplans, exhibitor kits, build windows, power, on-site control and breakdown — for the organiser, the exhibitor, or both if the brief says so." },
      { q: "Do you both design stands and manage halls?", a: "They are different jobs. We can do either or both, quoted as separate scopes so you are not paying for a hall manager to draw a booth." },
      { q: "Which halls do you know?", a: "Muscat convention and hotel exhibition spaces are the usual centre. Travelling shows are recce’d." },
    ],
    relatedServices: [
      { href: "/services/exhibition-stand-design-oman", label: "Stand design" },
      { href: "/services/exhibition-stand-construction-oman", label: "Stand construction" },
    ],
    relatedIndustries: [
      { href: "/industries/healthcare", label: "Healthcare" },
      { href: "/industries/maritime-logistics", label: "Maritime" },
    ],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "exhibition-stand-design-oman",
    nav: "Exhibition Stand Design",
    group: "exhibitions",
    title: "Exhibition Stand Design in Oman",
    h1: "Stand design for halls people actually walk",
    description:
      "Exhibition stand design in Oman focused on visitor flow, brand storytelling and buildable drawings for Muscat halls.",
    lede: "A stand is a small building with a three-day life. We design for the aisle, the conversation and the crate — not only for a hero render.",
    overview: [
      "Design starts with the brief’s job: meetings, product demo, hospitality, or a simple presence. Those jobs fight if they share one open square.",
      "Drawings we issue are meant to be built in Oman’s timelines: materials, graphics sizes, and a storage plan for crates.",
    ],
    includes: ["Concept", "3D", "Visitor flow", "Graphics layout", "Build-ready drawings", "Material notes"],
    capabilities: ["Meeting nooks", "Demo zones", "Bilingual graphics hierarchy", "Sustainable material options when specified"],
    formats: ["Island stands", "Inline booths", "Meeting suites", "Kiosk-scale presence"],
    oman: ["Hall lighting in Muscat can wash pastel brands. We spec contrast that still photographs."],
    approach: ["You approve a concept against a budget band. We will not design a palace for a kiosk invoice."],
    audience: "Exhibitors who care how the stand works at 11:00 on day two, not only at the unveiling.",
    faqs: [
      { q: "Do you design without building?", a: "Yes. Design-only is a defined scope. Construction can be added or taken by another builder to our drawings if you prefer." },
      { q: "How do Arabic and English sit on a stand?", a: "We design a hierarchy so neither language looks like a caption. Names and official titles are checked, not guessed." },
      { q: "Can you design for a small inline booth?", a: "Yes. Small stands need stricter editing, not less thought." },
    ],
    relatedServices: [
      { href: "/services/exhibition-stand-construction-oman", label: "Stand construction" },
      { href: "/services/event-branding-oman", label: "Event branding" },
    ],
    relatedIndustries: [
      { href: "/industries/automotive", label: "Automotive" },
      { href: "/industries/technology-telecom", label: "Technology" },
    ],
    relatedLocations: [muscat],
  },
  {
    slug: "exhibition-stand-construction-oman",
    nav: "Exhibition Stand Construction",
    group: "exhibitions",
    title: "Exhibition Stand Construction in Oman",
    h1: "Stand construction: build, finish, install, restore",
    description:
      "Exhibition stand construction in Oman covering fabrication, transport, installation and hall restoration for Muscat shows.",
    lede: "Construction is carpentry, graphics, electrics and a hall clock. We build to drawings and hand over a floor that can be staffed.",
    overview: [
      "This page is not a rewrite of stand design. Design decides the idea. Construction decides whether the idea stands up, lights up and comes down without a fight.",
      "Fabrication is planned for Muscat workshops and hall access. Shows in other cities get a crate list and a travel plan.",
    ],
    includes: ["Fabrication", "Graphics install", "Electrics", "Transport", "On-site finishing", "Breakdown"],
    capabilities: ["Custom scenic", "Reconfigurable systems where specified", "Night build windows"],
    formats: ["Custom islands", "System-plus-custom hybrids", "Reused scenic for roadshows"],
    oman: ["Hall contractors and organiser rules control tools and hours. We work inside them."],
    approach: ["Snagging happens before the exhibitor’s first guest, not during."],
    audience: "Exhibitors and designers who need a builder accountable on the floor.",
    faqs: [
      { q: "Can you build from another designer’s drawings?", a: "Yes, after a buildability review. We will flag what cannot be made in the time or the hall." },
      { q: "Do you store stands between shows?", a: "Storage can be arranged when the brief includes reuse. It is a line item, not a complimentary warehouse." },
      { q: "What about stands in Salalah?", a: "Simple builds may finish locally; complex scenic usually travels from Muscat with earlier freight." },
    ],
    relatedServices: [
      { href: "/services/exhibition-stand-design-oman", label: "Stand design" },
      { href: "/services/venue-logistics-oman", label: "Venue logistics" },
    ],
    relatedIndustries: [{ href: "/industries/luxury-retail", label: "Luxury & retail" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "product-launches-oman",
    nav: "Product Launches",
    group: "experiences",
    title: "Product Launch Events in Oman",
    h1: "Product launches engineered for the first look",
    description:
      "Product launch events in Oman with reveal choreography, press lines, lighting cues and content capture.",
    lede: "A launch is a timed reveal plus a room that can talk about the product afterwards. We plot both.",
    overview: [
      "Muscat launches live in hotels, showrooms and occasionally outdoor decks. The product — car, device, development, service — dictates load-in more than the floral moodboard.",
      "Press need a hero angle. Clients need hospitality. Staff need a demo that works. Those three paths are drawn separately.",
    ],
    includes: ["Reveal cues", "Press positions", "Demo power", "Lighting looks", "Content capture", "Guest flow"],
    capabilities: ["Vehicle load-in planning", "LED content desks", "Embargo timing"],
    formats: ["Press reveals", "Private client first looks", "Staff launches", "Public unveilings"],
    oman: ["Heat and sun angles punish outdoor reveals. We schedule and shade, or we move inside."],
    approach: ["The reveal cue is rehearsed. If it cannot be rehearsed, it is simplified."],
    audience: "Brand, automotive, real estate, technology and agency teams.",
    faqs: [
      { q: "Can you launch a vehicle in a Muscat hotel?", a: "If engineering signs off floor load and access. Otherwise we recommend a different site rather than risk the product." },
      { q: "Do you film the launch?", a: "Photography and videography can be in the same proposal, with a content brief so we are not guessing the cut." },
      { q: "How long should a launch last?", a: "Often 60–120 minutes of programme plus hospitality. Longer only if the product needs hands-on time." },
    ],
    relatedServices: [
      { href: "/services/led-screens-oman", label: "LED screens" },
      { href: "/services/photography-videography-oman", label: "Photography & videography" },
    ],
    relatedIndustries: [
      { href: "/industries/automotive", label: "Automotive" },
      { href: "/industries/technology-telecom", label: "Technology" },
    ],
    relatedLocations: [muscat],
  },
  {
    slug: "brand-activations-oman",
    nav: "Brand Activations",
    group: "experiences",
    title: "Brand Activations in Oman",
    h1: "Activations that respect the floor and still stop a guest",
    description:
      "Brand activations in Oman for malls, public sites and private previews, with bilingual hosts and a build that can vanish on time.",
    lede: "An activation is a conversation device in public space. It has to be legal, kind to circulation, and staffed by people who know the offer.",
    overview: [
      "Muscat malls and public sites have operating rules that kill last-minute builds. We design to those rules: height, power, noise, fire, and overnight work.",
      "Hosts work in Arabic and English. The next step — sample, QR, appointment — is obvious without a speech.",
    ],
    includes: ["Concept for the site", "Build", "Staff briefing", "Permit liaison", "Daily reset", "Strike"],
    capabilities: ["Mall common areas", "Pop-up counters", "Sampling with queue design"],
    formats: ["Mall activations", "Public previews", "Campus pop-ups"],
    oman: ["Friday peak and weekday lunch behave differently. Staffing follows the traffic, not a flat roster."],
    approach: ["We measure success as qualified interactions if you define them — not as ‘vibes’."],
    audience: "Retail, FMCG-style sampling, automotive displays, telecom and luxury houses.",
    faqs: [
      { q: "Can you run mall activations in Muscat?", a: "Yes, inside each centre’s rules. We do not promise a site we have not cleared." },
      { q: "Do you supply promotional staff?", a: "Yes, briefed to the brand tone and languages required. Staffing is a scoped service." },
      { q: "How fast can an activation be built?", a: "Simple counters in days; scenic rooms need weeks. The site’s night window is usually the limit." },
    ],
    relatedServices: [
      { href: "/services/event-staffing-oman", label: "Event staffing" },
      { href: "/services/roadshows-oman", label: "Roadshows" },
    ],
    relatedIndustries: [{ href: "/industries/luxury-retail", label: "Luxury & retail" }],
    relatedLocations: [muscat, sohar],
  },
  {
    slug: "gala-dinners-oman",
    nav: "Gala Dinners",
    group: "management",
    title: "Gala Dinners in Oman",
    h1: "Gala dinners with pacing, not just centrepieces",
    description:
      "Gala dinner production in Oman covering staging, hospitality sequence, entertainment cues and bilingual programme flow.",
    lede: "A dinner is a timed sequence: arrival, welcome, food, speeches, room energy. Flowers are not a plan.",
    overview: [
      "Muscat ballrooms can look generous and still fail if service, awards and a band fight for the same ten minutes. We write the sequence with the hotel banquet team, not against them.",
      "Hospitality may include a majlis arrival or kahwa — as a chapter, not a traffic jam at the door.",
    ],
    includes: ["Room plan", "Stage for speeches", "Service coordination", "Entertainment cues", "Lighting looks", "Show calling"],
    capabilities: ["Awards overlays", "Bilingual programmes", "Quiet VIP tables"],
    formats: ["Corporate galas", "Awards dinners", "National Day-adjacent evenings", "Association dinners"],
    oman: ["Service style and speech length should match the audience. We will cut entertainment before we cut dignity."],
    approach: ["The producer sits with banquet timing. The caller protects speeches from clattering plates."],
    audience: "Corporates, associations, luxury brands and official hosts.",
    faqs: [
      { q: "Can you include Omani welcome rituals in a gala?", a: "Yes — majlis, kahwa, dates or frankincense — timed so they do not stall seating." },
      { q: "Do you manage the menu?", a: "We coordinate with the hotel or caterer. Dietary and hospitality tone sit in the brief; we are not a restaurant." },
      { q: "What about entertainment?", a: "Live elements are sourced to the room. We do not drop in a novelty catalogue from another country." },
    ],
    relatedServices: [
      { href: "/services/award-ceremonies-oman", label: "Award ceremonies" },
      { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" },
    ],
    relatedIndustries: [
      { href: "/industries/banking-finance", label: "Banking" },
      { href: "/industries/corporate", label: "Corporate" },
    ],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "award-ceremonies-oman",
    nav: "Award Ceremonies",
    group: "management",
    title: "Award Ceremonies in Oman",
    h1: "Award ceremonies where names, timing and dignity hold",
    description:
      "Award ceremony production in Oman with winner flow, script control, lighting cues and bilingual name treatment.",
    lede: "Awards are a logistics problem disguised as a celebration. Misread names and stalled trophies are what guests remember.",
    overview: [
      "We build a winner path: holding, walk, handshake, photograph, exit. Scripts are checked with the host for pronunciation.",
      "Lighting and content support the name on screen. Music beds duck for speech, always.",
    ],
    includes: ["Script support", "Winner flow", "Stage management", "Screen content", "Photography positions", "Rehearsal"],
    capabilities: ["Large winner lists", "Category films", "Quiet protocol tables"],
    formats: ["Industry awards", "Internal recognition", "Education ceremonies"],
    oman: ["Official titles and honorifics are not decorative. We take the protocol pack as a production document."],
    approach: ["If the list is long, we design pace so the room does not die at award twelve."],
    audience: "Associations, corporates, schools and public bodies.",
    faqs: [
      { q: "How do you handle bilingual names?", a: "Arabic and English treatments are designed together. Pronunciation is confirmed with the host, not guessed by a caller." },
      { q: "Can awards sit inside a dinner?", a: "Yes, as a chapter with its own cues so service can pause cleanly." },
      { q: "Do you produce trophy moments only?", a: "We can. Full evening production is a wider scope." },
    ],
    relatedServices: [
      { href: "/services/gala-dinners-oman", label: "Gala dinners" },
      { href: "/services/event-production-oman", label: "Event production" },
    ],
    relatedIndustries: [{ href: "/industries/education", label: "Education" }],
    relatedLocations: [muscat],
  },
  {
    slug: "government-events-oman",
    nav: "Government Events",
    group: "management",
    title: "Government Event Management in Oman",
    h1: "Government events produced to a protocol pack",
    description:
      "Government event management in Oman for official openings, forums and commemorations, with bilingual materials and discreet crew.",
    lede: "Official programmes are not corporate galas with flags added. Order, language and restraint are the brief.",
    overview: [
      "We start with the host office’s protocol: who enters, who speaks, what may be filmed, which languages appear on titles. Production follows that pack.",
      "Crew are briefed to be competent and quiet. Technical looks support speeches. Spectacle is only added when asked.",
    ],
    includes: ["Protocol liaison", "Bilingual materials", "Arrival choreography", "Holding rooms", "Discreet technical", "Show calling"],
    capabilities: ["National Day-adjacent programmes", "Forum staging", "Media positions"],
    formats: ["Openings", "Commemorations", "Ministerial forums", "Public ceremonies"],
    oman: ["Governorate programmes still travel with a capital-quality cue sheet. Freight is planned, not hoped."],
    approach: ["We would rather decline a theatrical idea than embarrass a host."],
    audience: "Public-sector hosts, agencies and contractors supporting official gatherings.",
    faqs: [
      { q: "How do government events differ from corporate shows in Oman?", a: "Protocol order, bilingual accuracy, photography limits and a cooler technical tone. Entertainment is used sparingly." },
      { q: "Can you support National Day-related programmes?", a: "Yes, with flag etiquette, performance sourcing that is Omani, and a timeline that respects official diaries." },
      { q: "Do you publish government clients?", a: "Only with permission. This website does not invent a roster." },
    ],
    relatedServices: [
      { href: "/services/omani-folk-performance", label: "Omani folk performance" },
      { href: "/services/vip-luxury-events-oman", label: "VIP events" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat, duqm],
  },
  {
    slug: "vip-luxury-events-oman",
    nav: "VIP & Luxury",
    group: "experiences",
    title: "VIP and Luxury Events in Oman",
    h1: "VIP events where privacy is a production cue",
    description:
      "VIP and luxury event management in Oman for small high-touch gatherings, private dinners and discreet guest journeys.",
    lede: "Luxury in Oman is quiet competence: arrival that is private, a table that is ready, and staff who do not perform enthusiasm.",
    overview: [
      "Smaller rooms in Muscat hotels, residences and destination sites need as much plotting as a ballroom — sometimes more, because there is nowhere to hide a mistake.",
      "We plan car flow, greeting order, device policy and photography. Hospitality draws on majlis practice when the brief wants it.",
    ],
    includes: ["Arrival choreography", "Privacy plan", "Table and room design", "Discreet staffing", "Light technical", "Host support"],
    capabilities: ["Private client dinners", "Leadership hospitality", "Destination VIP chapters"],
    formats: ["Dinners", "Preview viewings", "Residence gatherings", "Small ceremonies"],
    oman: ["We do not claim palace venues we have not been asked to work. Residential work stays confidential."],
    approach: ["Fewer cues, better ones. We will cut scenic before we cut space to breathe."],
    audience: "Family offices, luxury houses, senior corporate hosts.",
    faqs: [
      { q: "Do you take very small guest counts?", a: "Yes. Twelve people can still need a producer if the stakes are high." },
      { q: "Can you work outside hotels?", a: "When access and permissions exist. We recce; we do not guess a residence’s power." },
      { q: "Is social posting allowed?", a: "Only to the host’s rule. Default is no." },
    ],
    relatedServices: [
      { href: "/services/omani-majlis-experiences", label: "Majlis experiences" },
      { href: "/services/destination-events-oman", label: "Destination events" },
    ],
    relatedIndustries: [{ href: "/industries/luxury-retail", label: "Luxury & retail" }],
    relatedLocations: [muscat, { href: "/locations/khasab", label: "Khasab" }],
  },
  {
    slug: "weddings-oman",
    nav: "Weddings",
    group: "experiences",
    title: "Wedding Event Management in Oman",
    h1: "Weddings produced with family flow and hotel reality",
    description:
      "Wedding event management in Muscat and Oman covering hotel and garden celebrations, guest flow, timing and hospitality.",
    lede: "A wedding in Oman is a family operation with production underneath. We hold timing, vendors and the room so hosts can be present.",
    overview: [
      "Muscat hotel weddings, garden looks and mixed-tradition celebrations each need a different circulation. We plan arrival, photography, dinner and send-off as chapters.",
      "We work with the couple’s chosen hosts on cultural elements that are actually theirs — not a copied ceremonial menu from another Gulf market.",
    ],
    includes: ["Timeline", "Vendor coordination", "Room and table plans", "Technical for speeches and music", "Guest flow", "Show-day management"],
    capabilities: ["Hotel liaison", "Garden fallback plans", "Bilingual programmes"],
    formats: ["Hotel ballroom weddings", "Garden receptions", "Intimate dinners"],
    oman: ["Peak season hotels book early. Weather and dress need honest outdoor plans."],
    approach: ["We are producers, not a substitute family. Decisions stay with the hosts; we keep the clock."],
    audience: "Couples and families who want professional show-day control in Oman.",
    faqs: [
      { q: "Do you plan the whole wedding or only production?", a: "Either. Some families have a planner and need a producer. Others want both in one team. The proposal says which." },
      { q: "Can you work in Salalah or Nizwa?", a: "Yes, with destination logistics. Muscat remains the usual centre." },
      { q: "Do you invent traditions?", a: "No. We produce what the family actually wants, with respect." },
    ],
    relatedServices: [
      { href: "/services/event-production-oman", label: "Event production" },
      { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" },
    ],
    relatedIndustries: [{ href: "/industries/hospitality-tourism", label: "Hospitality" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "destination-events-oman",
    nav: "Destination Events",
    group: "experiences",
    title: "Destination Events in Oman",
    h1: "Destination events: landscape as a chapter, not the whole brief",
    description:
      "Destination event management in Oman for multi-site programmes across Muscat, Dhofar, the Hajar interior and Musandam.",
    lede: "Oman rewards destination briefs if they are still events: timed, hosted, technically competent. A landscape is not a run of show.",
    overview: [
      "We sequence cities and sites so guests are not exhausted by transfers. Working sessions get real rooms. Cultural and landscape chapters have start and end times.",
      "Khareef, summer heat and sea state in Musandam are treated as production risks with backups already designed.",
    ],
    includes: ["Itinerary as run of show", "Venue mix", "Transfers", "Technical at each stop", "Hospitality", "Contingency programmes"],
    capabilities: ["Hajar offsites", "Coastal evenings", "Dhofar seasonal programmes", "Musandam incentives"],
    formats: ["Incentive trips", "Leadership journeys", "Tourism forums with site chapters"],
    oman: ["We will not sell a tour-desk itinerary dressed as event management."],
    approach: ["Every outdoor cue has an indoor twin if weather or protocol requires it."],
    audience: "Incentive buyers, tourism hosts, corporates wanting Oman without improvisation.",
    faqs: [
      { q: "Can destination events include Nizwa, Salalah and Khasab?", a: "Yes, as named chapters with logistics. Not all three in forty-eight hours." },
      { q: "Do you arrange hotels and flights?", a: "We can coordinate within the event plan. Airlines and hotels remain the contracted parties unless the brief says otherwise." },
      { q: "How do you avoid a tourism brochure feel?", a: "Protect working sessions, limit moves, and host cultural stops instead of sightseeing lists." },
    ],
    relatedServices: [
      { href: "/services/corporate-events-oman", label: "Corporate events" },
      { href: "/services/dhofar-cultural-programming", label: "Dhofar programming" },
    ],
    relatedIndustries: [{ href: "/industries/hospitality-tourism", label: "Hospitality & tourism" }],
    relatedLocations: [muscat, salalah, { href: "/locations/nizwa", label: "Nizwa" }, { href: "/locations/khasab", label: "Khasab" }],
  },
  {
    slug: "roadshows-oman",
    nav: "Roadshows",
    group: "experiences",
    title: "Roadshows in Oman",
    h1: "Roadshows that survive the drive between cities",
    description:
      "Event roadshows in Oman covering Muscat, Sohar, Duqm and Salalah with travelling kits, crew housing and consistent brand delivery.",
    lede: "A roadshow is a touring production. If the crate list is wishful, city three will look like a different campaign.",
    overview: [
      "We design a kit that fits the smallest room on the tour, then add local scale in Muscat if needed. Crew rest and freight windows are on the Gantt chart.",
      "Messages stay consistent; hospitality can localise — kahwa in one city, a shorter industrial breakfast in another.",
    ],
    includes: ["Tour grid", "Travelling technical", "Local labour plans", "Brand consistency", "Reset checklists", "Strike between cities"],
    capabilities: ["Muscat–Sohar–Duqm sequences", "Dealer tours", "Stakeholder briefings"],
    formats: ["Product tours", "Internal leadership tours", "Public-sector briefings"],
    oman: ["Duqm and Salalah need more calendar than Sohar. We will say if the proposed dates are theatre."],
    approach: ["Same producer across cities. Local crews change; the cue sheet does not."],
    audience: "Brands, energy, automotive, government campaigns needing national presence.",
    faqs: [
      { q: "Which cities make sense on an Oman roadshow?", a: "Muscat plus Sohar and/or Duqm for industrial briefs; Salalah when the south is the point. Nizwa or Sur when the audience is actually there." },
      { q: "Can the same stand travel?", a: "If it was designed to crate. Many Muscat islands cannot. We design touring versions." },
      { q: "How many days between cities?", a: "Enough to strike, travel, sleep and recce. Overnight heroics are a risk, not a badge." },
    ],
    relatedServices: [
      { href: "/services/brand-activations-oman", label: "Activations" },
      { href: "/services/venue-logistics-oman", label: "Venue logistics" },
    ],
    relatedIndustries: [
      { href: "/industries/automotive", label: "Automotive" },
      { href: "/industries/maritime-logistics", label: "Maritime" },
    ],
    relatedLocations: [muscat, sohar, duqm, salalah],
  },
  {
    slug: "event-staffing-oman",
    nav: "Event Staffing",
    group: "staffing",
    title: "Event Staffing in Oman",
    h1: "Event staffing: hosts, ushers and crew who already know the sheet",
    description:
      "Event staffing in Oman including bilingual hosts, ushers, registration teams and technical crew briefed to the run of show.",
    lede: "Staffing is not a row of unidentified people in black. It is roles, languages, briefings and a floor lead.",
    overview: [
      "Muscat programmes often need Arabic and English at the door, calm ushers for mixed protocol rooms, and technical hands who take cues from the caller.",
      "We brief from the same document as production so hosts are not inventing the offer.",
    ],
    includes: ["Role design", "Recruitment against the brief", "Briefing", "Floor lead", "Show-day management", "Wrap"],
    capabilities: ["Bilingual hosts", "Registration teams", "Stagehands", "Discreet VIP support"],
    formats: ["Conferences", "Galas", "Activations", "Exhibitions"],
    oman: ["Dress codes and gender mix on the floor follow the host’s culture and the venue’s rules."],
    approach: ["We would rather staff fewer, better-briefed people than fill a quota."],
    audience: "Any programme that meets guests.",
    faqs: [
      { q: "Can event companies provide Arabic and English support?", a: "Yes. Hosting, registration and floor language mix are specified in the brief and staffed accordingly." },
      { q: "Do you supply security?", a: "Licensed security is coordinated when the brief requires it, as a named vendor — not as untrained ushers." },
      { q: "Can staffing be booked without full production?", a: "Yes. You still receive a briefing pack so the team is not guessing." },
    ],
    relatedServices: [
      { href: "/services/registration-guest-management-oman", label: "Registration" },
      { href: "/services/brand-activations-oman", label: "Activations" },
    ],
    relatedIndustries: [{ href: "/industries/corporate", label: "Corporate" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "registration-guest-management-oman",
    nav: "Registration",
    group: "staffing",
    title: "Registration and Guest Management in Oman",
    h1: "Registration that feels like hospitality, not a queue",
    description:
      "Registration and guest management in Oman covering badging, name protocol, queue design and bilingual welcome.",
    lede: "Arrival is the first production cue. If the line is chaotic, the plenary starts on the back foot.",
    overview: [
      "We design the desk, the badge, the exception handling and the greeter roles. Protocol names are printed as the host approved them.",
      "Accessibility, overflow and late VIP arrivals are planned, not solved with a wave.",
    ],
    includes: ["Queue design", "Badge production liaison", "Desk staffing", "Exception handling", "Data handling rules", "Door reports"],
    capabilities: ["Multi-language desks", "Embargoed guest lists", "Session scanning when specified"],
    formats: ["Congresses", "Galas", "Official programmes"],
    oman: ["Honorifics and dual-script names need extra proofing time. We build that into pre-production."],
    approach: ["Personal data is handled to the host’s policy. We do not keep lists ‘just in case’."],
    audience: "Conference owners and official hosts.",
    faqs: [
      { q: "Can you integrate with our registration platform?", a: "Often yes. We need access rules early. If the platform is locked, we design the physical layer around it." },
      { q: "Do you print badges?", a: "We can coordinate print and on-site reprint. It is specified, not assumed." },
      { q: "How do you handle uninvited arrivals?", a: "A named exception process with the host’s representative, not an argument at the ribbon." },
    ],
    relatedServices: [
      { href: "/services/conference-management-oman", label: "Conference management" },
      { href: "/services/event-staffing-oman", label: "Event staffing" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat],
  },
  {
    slug: "audio-visual-oman",
    nav: "Audio Visual",
    group: "production",
    title: "Audio Visual Services in Oman",
    h1: "Audio visual specified for speech, recording and the actual room",
    description:
      "Audio visual services in Oman for conferences, ceremonies and launches, including sound, projection, switching and recording.",
    lede: "AV is not a stack of black boxes. It is coverage, gain-before-feedback, recording paths and an operator who has rehearsed.",
    overview: [
      "Hotel ballrooms in Muscat swallow speech. Gardens leak it. OCEC halls need a different approach again. We spec to measurements and a recce, not to a catalogue page.",
      "Interpretation, recording and streams are first-class if the brief includes them — not a laptop on a banquet table.",
    ],
    includes: ["PA design", "Switching", "Recording", "Operator crew", "Backup paths", "Show comms"],
    capabilities: ["Speech-first rooms", "Hybrid feeds", "Content playback"],
    formats: ["Conferences", "Launches", "Ceremonies"],
    oman: ["Power quality on remote sites is part of the spec. Duqm and plant rooms get isolation and spares."],
    approach: ["We would rather hang fewer, better-placed speakers than a wall of unused boxes."],
    audience: "Anyone whose event depends on being heard and recorded.",
    faqs: [
      { q: "Do you use the hotel’s in-house AV?", a: "When it is adequate. When it is not, we say so and spec a supplement rather than fighting the house kit silently." },
      { q: "Can you support simultaneous interpretation?", a: "Yes, as a designed feed, not a shared handheld." },
      { q: "Is LED part of AV?", a: "LED is specified alongside AV; it has its own page because pixel pitch and content ops are a distinct job." },
    ],
    relatedServices: [
      { href: "/services/led-screens-oman", label: "LED screens" },
      { href: "/services/lighting-sound-oman", label: "Lighting & sound" },
    ],
    relatedIndustries: [{ href: "/industries/healthcare", label: "Healthcare" }],
    relatedLocations: [muscat, duqm],
  },
  {
    slug: "stage-design-oman",
    nav: "Stage Design",
    group: "production",
    title: "Stage Design in Oman",
    h1: "Stage design for sightlines, cameras and bilingual titles",
    description:
      "Stage design in Oman for plenaries, ceremonies and galas, with camera-aware scenic and Arabic–English title treatment.",
    lede: "A stage has to work from the back row and from the official photographer’s lens. We design both.",
    overview: [
      "Scenic in Oman rooms must respect hanging limits, fire rules and the fact that many guests will watch on phones afterwards. Titles need a bilingual hierarchy that does not look like subtitles.",
      "We produce drawings that construction and lighting can actually use.",
    ],
    includes: ["Concept", "Sightline studies", "Material notes", "Title design space", "Camera positions", "Build liaison"],
    capabilities: ["Soft scenic", "Architectural frames", "Reveal gags when justified"],
    formats: ["Plenary stages", "Ceremony sets", "Talk-show formats"],
    oman: ["Official crests and flags are placed to protocol, not to a designer’s crop."],
    approach: ["Form follows the speaker. Decoration that hides a face is cut."],
    audience: "Conference and ceremony hosts.",
    faqs: [
      { q: "Can a stage travel on a roadshow?", a: "A touring version can. Capital-scale scenic usually cannot. We design to the tour." },
      { q: "Do you build the stage as well?", a: "Design and construction can be one proposal or split. Drawings are build-ready either way." },
      { q: "How do you handle LED in the set?", a: "The wall is part of the architecture, with content safe areas for bilingual lower thirds." },
    ],
    relatedServices: [
      { href: "/services/event-production-oman", label: "Event production" },
      { href: "/services/led-screens-oman", label: "LED screens" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat],
  },
  {
    slug: "lighting-sound-oman",
    nav: "Lighting & Sound",
    group: "production",
    title: "Lighting and Sound for Events in Oman",
    h1: "Lighting and sound as one plot for speech and atmosphere",
    description:
      "Lighting and sound for Oman events, specified together so looks, microphones and playback support the same cue sheet.",
    lede: "Splitting lighting and sound between vendors is how cues drift. We plot them as one show.",
    overview: [
      "Speech-first lighting still has to flatter formal dress. Sound has to reach the back without punishing the front tables. Those two sentences are the brief for most Muscat dinners.",
      "Entertainment looks are a different plot and are only added when the programme needs them.",
    ],
    includes: ["Lighting design", "PA design", "Wireless plan", "Cueing", "Operators", "Spares"],
    capabilities: ["Gala looks", "Plenary evenness", "Outdoor with wind plans"],
    formats: ["Dinners", "Conferences", "Ceremonies"],
    oman: ["Garden moisture in Khareef and dust on interior roads both affect kit. We spec IP ratings and covers."],
    approach: ["Looks are named and rehearsed. Busking a whole ceremony is not a method."],
    audience: "Hosts who care how people look and how they hear.",
    faqs: [
      { q: "Why are lighting and sound on one page?", a: "Because they share the cue sheet and the ceiling. Separate rental pages often hide the same crew fighting each other." },
      { q: "Can you work with house lighting?", a: "As a base. Most ballrooms still need a show layer for faces and stage." },
      { q: "Do you provide DJs or bands?", a: "We can source playback or live music to the plot. It is a separate entertainment line." },
    ],
    relatedServices: [
      { href: "/services/audio-visual-oman", label: "Audio visual" },
      { href: "/services/event-production-oman", label: "Event production" },
    ],
    relatedIndustries: [{ href: "/industries/corporate", label: "Corporate" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "led-screens-oman",
    nav: "LED Screens",
    group: "production",
    title: "LED Screens for Events in Oman",
    h1: "LED specified by viewing distance, not by square metres",
    description:
      "LED screens for Oman events with pixel pitch, content operations, processing and rehearsal for Muscat rooms and touring shows.",
    lede: "An LED wall that is too coarse, too bright or unfed is worse than no wall. We spec pitch, sit a content operator, and rehearse.",
    overview: [
      "Viewing distance in a Muscat ballroom is not the same as an OCEC hall. We choose pitch accordingly and build safe areas for bilingual graphics.",
      "Content ops means someone can recover a failed clip without stopping the speaker.",
    ],
    includes: ["Pitch specification", "Processing", "Content desk", "Calibration", "Backup players", "Crew"],
    capabilities: ["IMAG", "Scenic LED", "Outdoor with brightness headroom"],
    formats: ["Launches", "Plenaries", "Exhibitions"],
    oman: ["Sun on glass facades can fight LED. We recce ambient light."],
    approach: ["No wall is installed without a content rehearsal, even if the client ‘only has slides’."],
    audience: "Launch, conference and exhibition teams.",
    faqs: [
      { q: "LED or projection in Muscat rooms?", a: "Depends on ambient light, budget and content. We recommend; we do not sell a wall by default." },
      { q: "Can LED travel to Duqm?", a: "A touring set can. Large scenic walls usually cannot without serious freight time." },
      { q: "Do you create the content?", a: "Motion content can be scoped. Many clients supply; we still need specs and a desk." },
    ],
    relatedServices: [
      { href: "/services/product-launches-oman", label: "Product launches" },
      { href: "/services/audio-visual-oman", label: "Audio visual" },
    ],
    relatedIndustries: [{ href: "/industries/technology-telecom", label: "Technology" }],
    relatedLocations: [muscat],
  },
  {
    slug: "event-branding-oman",
    nav: "Event Branding",
    group: "branding",
    title: "Event Branding in Oman",
    h1: "Event branding as a guest journey, not scattered logos",
    description:
      "Event branding in Oman covering arrival, stage, table and digital surfaces in Arabic and English as one system.",
    lede: "Branding is the through-line from kerb to stage. If those surfaces disagree, the organisation looks undecided.",
    overview: [
      "We map every guest-facing surface, then edit. Not every lollipop sign needs a manifesto.",
      "Arabic and English are designed as a pair. Official names are proofed.",
    ],
    includes: ["Look development", "Surface map", "Print liaison", "Stage integration", "Digital templates", "On-site dressing"],
    capabilities: ["Bilingual systems", "Protocol-safe official looks", "Retail-accurate colour"],
    formats: ["Conferences", "Galas", "Exhibitions", "Activations"],
    oman: ["National colours and official marks are used only when authorised and correctly drawn."],
    approach: ["We present a system, not fifty disconnected files."],
    audience: "Brand and comms teams.",
    faqs: [
      { q: "Do you print everything?", a: "We design and coordinate print. Production partners are named in the estimate." },
      { q: "Can you work from our brand guidelines?", a: "Yes. We will say when a guideline written for A4 fails on a 12-metre wall." },
      { q: "Is signage included?", a: "Wayfinding has its own page because circulation is a different problem from brand atmosphere." },
    ],
    relatedServices: [
      { href: "/services/event-signage-oman", label: "Event signage" },
      { href: "/services/stage-design-oman", label: "Stage design" },
    ],
    relatedIndustries: [{ href: "/industries/luxury-retail", label: "Luxury & retail" }],
    relatedLocations: [muscat],
  },
  {
    slug: "event-signage-oman",
    nav: "Event Signage",
    group: "branding",
    title: "Event Signage in Oman",
    h1: "Signage that moves people without shouting",
    description:
      "Event signage and wayfinding in Oman for conferences and ceremonies, with Arabic–English hierarchy and protocol names.",
    lede: "Wayfinding is information design. Guests in a hurry should not have to decode a poster.",
    overview: [
      "We walk the route: car, door, desk, room, prayer space, dinner. Signs sit on that route, in the languages the audience actually uses.",
      "Temporary vinyl that damages hotel surfaces is not a plan. We spec methods venues accept.",
    ],
    includes: ["Route map", "Message list", "Bilingual layout", "Fabrication liaison", "Install", "Strike"],
    capabilities: ["Protocol name boards", "Session changes", "Accessible routes"],
    formats: ["Congresses", "Official programmes", "Multi-room hotels"],
    oman: ["Spelling of places and titles is checked against the host, not against muscle memory."],
    approach: ["Fewer, larger, better placed."],
    audience: "Conference and ceremony organisers.",
    faqs: [
      { q: "When should signage be locked?", a: "After the room plan is stable. Late session changes need a reprint method, not hope." },
      { q: "Digital or printed?", a: "Both have a place. Digital helps last-minute grids; print still wins in sunlight and protocol rooms." },
      { q: "Can you sign a whole OCEC-scale hall?", a: "Yes, as a wayfinding system, not as random foam boards." },
    ],
    relatedServices: [
      { href: "/services/event-branding-oman", label: "Event branding" },
      { href: "/services/conference-management-oman", label: "Conference management" },
    ],
    relatedIndustries: [{ href: "/industries/education", label: "Education" }],
    relatedLocations: [muscat],
  },
  {
    slug: "photography-videography-oman",
    nav: "Photography & Videography",
    group: "production",
    title: "Event Photography and Videography in Oman",
    h1: "Coverage planned like a camera plot, not a guest with a phone",
    description:
      "Event photography and videography in Oman for official records, press and social, with consent and protocol respected.",
    lede: "Cameras need positions, lighting that agrees, and a brief for what must exist at 23:00.",
    overview: [
      "Official programmes may limit angles. Galas want the table and the speech. Launches want the product. We crew to the brief, not to a one-size package.",
      "Delivery formats and usage rights are written down. We do not assume global advertising rights from a ceremony.",
    ],
    includes: ["Shot list", "Positions", "Lighting liaison", "Edit", "Official selects", "Usage notes"],
    capabilities: ["Protocol-sensitive coverage", "Multi-cam speeches", "Social cuts"],
    formats: ["Ceremonies", "Conferences", "Launches", "Weddings"],
    oman: ["Consent and cultural comfort around photography are briefed to the crew."],
    approach: ["The photographer sits in the production meeting, not in the corridor at doors."],
    audience: "Hosts who need an official record and usable content.",
    faqs: [
      { q: "Can you film and photograph the same event?", a: "Yes, with two briefs so they do not fight for the same angle." },
      { q: "How fast are selects?", a: "Agreed in the proposal. Same-evening social cuts are possible if crewed for it." },
      { q: "Do you drone?", a: "Only where permits and the site allow. Many urban and official sites will not." },
    ],
    relatedServices: [
      { href: "/services/product-launches-oman", label: "Product launches" },
      { href: "/services/government-events-oman", label: "Government events" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "venue-logistics-oman",
    nav: "Venue & Logistics",
    group: "management",
    title: "Venue Coordination and Event Logistics in Oman",
    h1: "Venues, permits, freight and load-in as a single operations sheet",
    description:
      "Venue coordination and event logistics in Oman covering permits, power, transport, inter-city freight and load-in windows.",
    lede: "Creative dies in a dock that was never booked. Logistics is the event’s skeleton.",
    overview: [
      "We map access, docks, generators, overnight labour and the drive between Muscat and the named city.",
      "Permits sit with the host and venue; we manage the production side of the paperwork so it is not a surprise on build day.",
    ],
    includes: ["Venue liaison", "Load-in plans", "Freight", "Power", "Crew housing", "Risk notes"],
    capabilities: ["Multi-city freight", "Industrial site access windows", "Hotel engineering diplomacy"],
    formats: ["Any produced event that moves kit or people"],
    oman: ["Duqm and Khareef Salalah punish optimistic courier culture. We put days on the chart."],
    approach: ["If a date cannot be freighted honestly, we say no before you print invitations."],
    audience: "Producers, agencies and in-house teams moving shows across Oman.",
    faqs: [
      { q: "Do you obtain every permit?", a: "We coordinate production-related approvals with venues and hosts. Some licences remain the organiser’s legal duty; we will name them." },
      { q: "Can you move a show from Muscat to Salalah in three days?", a: "Sometimes a light kit. Rarely a full scenic show. We will not pretend otherwise." },
      { q: "Generators on sites?", a: "Specified when house power is a risk, with load calculations — not a silent diesel next to speeches." },
    ],
    relatedServices: [
      { href: "/services/roadshows-oman", label: "Roadshows" },
      { href: "/services/event-production-oman", label: "Event production" },
    ],
    relatedIndustries: [{ href: "/industries/oil-gas-energy", label: "Energy" }],
    relatedLocations: [muscat, duqm, sohar, salalah],
  },
  {
    slug: "traditional-omani-hospitality",
    nav: "Omani Hospitality",
    group: "cultural",
    title: "Traditional Omani Hospitality for Events",
    h1: "Omani hospitality rituals designed into the guest journey",
    description:
      "Traditional Omani hospitality for events in Muscat and across Oman, including kahwa, dates, halwa and frankincense as timed welcome chapters.",
    lede: "Hospitality here has a grammar: welcome, scent, coffee, dates, conversation. We produce that grammar so it does not collide with registration.",
    overview: [
      "This is not a copied live-cooking menu from another country. Kahwa, Omani dates, halwa and luban belong to local practice and are staged with hosts who know the etiquette.",
      "The ritual is a chapter with a beginning and an end, then guests move. It is not an endless queue of trays blocking the door.",
    ],
    includes: ["Welcome design", "Host briefing", "Kahwa service plan", "Dates and halwa presentation", "Scenting plan", "Timing with registration"],
    capabilities: ["Official arrivals", "Corporate welcomes", "Wedding chapters"],
    formats: ["Majlis arrivals", "Foyer rituals", "Dinner pre-functions"],
    oman: ["Etiquette differs by family and region. We take the host’s lead rather than inventing a pageant."],
    approach: ["Better one well-hosted line than five decorative stations nobody staffs."],
    audience: "Official, corporate and private hosts who want the welcome to feel Omani.",
    faqs: [
      { q: "Is this the same as a generic ‘Arabic coffee station’?", a: "No. Service, vessels, pacing and frankincense are planned as Omani hospitality, with hosts briefed to etiquette — not as a buffet extra." },
      { q: "Can this sit inside a modern conference?", a: "Yes, as a timed welcome before sessions, not during a keynote." },
      { q: "Do you provide the coffee team?", a: "We source and brief. Quality of service is part of the production, not a surprise vendor at the door." },
      { q: "Can hospitality change for Ramadan or Eid?", a: "Yes. Ramadan welcomes are quieter and timed around iftar. Eid gatherings can be more celebratory, still with kahwa, dates and host etiquette rather than a copied party menu." },
    ],
    relatedServices: [
      { href: "/services/omani-majlis-experiences", label: "Majlis experiences" },
      { href: "/services/frankincense-welcome-rituals", label: "Frankincense welcome" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "omani-majlis-experiences",
    nav: "Majlis Experiences",
    group: "cultural",
    title: "Omani Majlis Experiences for Events",
    h1: "Majlis reception designed as architecture and etiquette",
    description:
      "Omani majlis experiences for events, covering seating, host roles, honour order and a reception that still meets a show clock.",
    lede: "A majlis is a social room with rules. We design seating, shade, scent and host roles so honour and timing can coexist.",
    overview: [
      "Corporate and official briefs in Oman often want a majlis chapter before a modern plenary. That only works if the majlis is a real room — not a couple of couches beside a speaker tower.",
      "Honour order, introductions and photography limits are written into the cue sheet.",
    ],
    includes: ["Spatial design", "Seating plan", "Host choreography", "Hospitality integration", "Acoustic calm", "Transition into the main room"],
    capabilities: ["Outdoor shaded majlis", "Indoor ballroom transformations", "VIP-only rooms"],
    formats: ["Official arrivals", "Leadership hospitality", "Wedding welcomes"],
    oman: ["We do not stage a caricature. Materials and service follow the host’s standard."],
    approach: ["The majlis ends. Guests are moved with dignity when the programme requires it."],
    audience: "Official and private hosts, destination programmes, VIP dinners.",
    faqs: [
      { q: "Can a majlis work for 300 guests?", a: "As a flowing welcome, yes, with multiple seating clusters and enough hosts. As a single conversation room, no." },
      { q: "Indoor or outdoor?", a: "Climate decides. Muscat summer and Salalah humidity argue for controlled rooms." },
      { q: "Is this suitable for international guests?", a: "Yes, if hosts explain the etiquette lightly. We brief hosts to welcome without lecturing." },
    ],
    relatedServices: [
      { href: "/services/vip-luxury-events-oman", label: "VIP events" },
      { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" },
    ],
    relatedIndustries: [{ href: "/industries/corporate", label: "Corporate" }],
    relatedLocations: [muscat, { href: "/locations/nizwa", label: "Nizwa" }],
  },
  {
    slug: "frankincense-welcome-rituals",
    nav: "Frankincense Welcome",
    group: "cultural",
    title: "Frankincense Welcome Rituals in Oman",
    h1: "Frankincense as an arrival note, not a souvenir stall",
    description:
      "Frankincense welcome rituals for events in Oman, using luban scenting and Dhofari context as a designed hospitality cue.",
    lede: "Luban is part of Oman’s sensory identity. Used well, it marks a threshold. Used badly, it is smoke in a fire lane.",
    overview: [
      "We place scenting where guests actually arrive, with ventilation and venue rules respected. A short explanation can sit for international guests without becoming a lecture.",
      "Dhofar programmes can go deeper — harvest context, not a fake market. Muscat programmes keep it as a refined welcome.",
    ],
    includes: ["Scent plan", "Venue compliance", "Host notes", "Threshold design", "Pairing with kahwa", "Strike"],
    capabilities: ["Official arrivals", "Hotel foyers", "Salalah seasonal programmes"],
    formats: ["Welcome rituals", "Exhibition openings", "Destination dinners"],
    oman: ["We source quality resin and proper burners. Hotel fire rules always win."],
    approach: ["Subtle and timed. If the venue forbids it, we do not smuggle it."],
    audience: "Tourism, official and corporate hosts wanting an Omani sensory cue.",
    faqs: [
      { q: "Will hotels allow frankincense?", a: "Many will with controls; some will not. We ask before we design it into the guest journey." },
      { q: "Is this only for Salalah?", a: "No. It is Omani. Salalah programmes can carry more cultural depth." },
      { q: "Can guests take resin home?", a: "As a considered gift, yes. As a cluttered stall at the cloakroom, no." },
    ],
    relatedServices: [
      { href: "/services/dhofar-cultural-programming", label: "Dhofar programming" },
      { href: "/services/traditional-omani-hospitality", label: "Omani hospitality" },
    ],
    relatedIndustries: [{ href: "/industries/hospitality-tourism", label: "Hospitality & tourism" }],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "omani-folk-performance",
    nav: "Omani Folk Performance",
    group: "cultural",
    title: "Omani Folk Performance for Events",
    h1: "Traditional performance sourced with respect: Razha, Al-Azi and approved troupes",
    description:
      "Omani folk performance for events including Razha and Al-Azi, sourced from appropriate troupes and cued inside the programme.",
    lede: "Traditional performance is not decoration. It has regional form, costume and timing. We book what belongs, then cue it like any other show element.",
    overview: [
      "Razha and Al-Azi are among the performance languages associated with Oman. We source troupes who actually work in those forms rather than substituting a generic Gulf set.",
      "The piece has an in and an out. Speeches are not talked over. Space and sightlines are plotted.",
    ],
    includes: ["Casting against the brief", "Rehearsal with the caller", "Staging space", "Audio for voice and percussion", "Costume logistics", "Cueing"],
    capabilities: ["Official ceremonies", "National Day-adjacent evenings", "Heritage dinners"],
    formats: ["Short ceremonial pieces", "Processional welcomes", "Stage features"],
    oman: ["We do not offer Al Ayyala or other non-Omani signature acts as a relabelled product."],
    approach: ["If the room cannot honour the performance, we recommend not doing it."],
    audience: "Official hosts, cultural evenings, destination programmes.",
    faqs: [
      { q: "Can you guarantee a specific troupe?", a: "We propose availability. National dates book early." },
      { q: "Is this suitable for international conferences?", a: "As a short, well-hosted welcome, yes. As a 40-minute interruption to a scientific grid, no." },
      { q: "Do you choreograph new pieces?", a: "We produce and stage. Creative authorship stays with the performers unless a collaboration is briefed." },
    ],
    relatedServices: [
      { href: "/services/government-events-oman", label: "Government events" },
      { href: "/services/gala-dinners-oman", label: "Gala dinners" },
    ],
    relatedIndustries: [{ href: "/industries/government-public-sector", label: "Government" }],
    relatedLocations: [muscat, { href: "/locations/nizwa", label: "Nizwa" }],
  },
  {
    slug: "dhofar-cultural-programming",
    nav: "Dhofar Programming",
    group: "cultural",
    title: "Dhofar Cultural Programming for Events",
    h1: "Dhofar programming for Salalah: climate, Bar’ah and Khareef-season hospitality",
    description:
      "Dhofar cultural programming for Salalah events, including Khareef-season constraints, local performance such as Bar’ah, and frankincense context.",
    lede: "Dhofar is not a plugin for a Muscat gala. Performance, foodways and weather are local. We programme with people who work there.",
    overview: [
      "Khareef gatherings, hotel launches and incentive groups often want a Dhofari chapter. We source locally appropriate music and dance — including Bar’ah where it fits — and we plan moisture, inventory and outdoor risk.",
      "Frankincense context can be a hosted moment, not a fake souq.",
    ],
    includes: ["Local performer sourcing", "Weather plans", "Hospitality pairing", "Permissions", "Cueing", "Guest explanation notes"],
    capabilities: ["Khareef overlays", "Resort evenings", "Tourism forums"],
    formats: ["Cultural nights", "Welcome ceremonies", "Festival-adjacent private programmes"],
    oman: ["We do not import a capital-city entertainment menu and rename it Dhofar."],
    approach: ["Recce in season if the brief is outdoor. Photographs lie in monsoon mist."],
    audience: "Tourism hosts, corporates and hotels working in Salalah.",
    faqs: [
      { q: "Can you organise events in Salalah during Khareef?", a: "Yes, with earlier holds, humidity-aware production and indoor fallbacks." },
      { q: "What is Bar’ah in this context?", a: "A Dhofari performance tradition we may source when the brief and the troupe fit — not a guaranteed party trick." },
      { q: "Do Muscat crews run the whole show?", a: "Key production travels; cultural programming is local. The caller still owns the clock." },
    ],
    relatedServices: [
      { href: "/services/destination-events-oman", label: "Destination events" },
      { href: "/services/frankincense-welcome-rituals", label: "Frankincense welcome" },
    ],
    relatedIndustries: [{ href: "/industries/hospitality-tourism", label: "Hospitality & tourism" }],
    relatedLocations: [salalah],
  },
  {
    slug: "live-entertainment-oman",
    nav: "Live Entertainment",
    group: "experiences",
    title: "Live Entertainment for Events in Oman",
    h1: "Live entertainment sourced for the actual Oman room",
    description:
      "Live entertainment for events in Oman, including music and performance booked to the brief, cued inside the run of show, and sized for Muscat rooms or travelling programmes.",
    lede: "Entertainment is a production line, not a party pack. We source what the room can honour, then give it an in, an out, and a volume that does not drown speeches.",
    overview: [
      "Corporate dinners, hotel celebrations and destination evenings in Oman often want live music or a short performance. The failure mode is a catalogue act that ignores Arabic and English audiences, venue noise limits, or a ceremony that still has names to read.",
      "We treat riders, power, staging space and changeovers as documents. Omani folk performance is a separate discipline when the brief wants heritage; this page is for contemporary live elements that still have to sit inside a produced programme.",
    ],
    includes: ["Casting against the brief", "Rider review", "Staging and power", "Sound for voice and music", "Cueing with the caller", "Changeover timing"],
    capabilities: ["Dinner entertainment", "Reception sets", "Award-show features", "Hotel celebrations"],
    formats: ["Small live ensembles", "Playback with a live feature", "Ceremonial openers"],
    oman: [
      "We do not publish a novelty-act catalogue copied from another market. If a request cannot be met in the room, we say so before contracts harden.",
    ],
    approach: ["Book what belongs. Rehearse the join to the speeches. Keep the caller on comms."],
    audience: "Corporate, hotel, private and destination hosts who want live elements without losing the programme.",
    faqs: [
      {
        q: "Do you provide bands and DJs in Oman?",
        a: "We can source live music or playback to the plot. It is a line in the proposal, not an assumed add-on. Availability on National Day-adjacent dates books early.",
      },
      {
        q: "Can entertainment sit inside a government or official programme?",
        a: "Only when the host asks for it and the tone fits. Official rooms usually need shorter, quieter features than a gala.",
      },
      {
        q: "Is this the same as Omani folk performance?",
        a: "No. Heritage forms such as Razha or Al-Azi have their own page and sourcing rules. This page covers contemporary live entertainment.",
      },
    ],
    relatedServices: [
      { href: "/services/gala-dinners-oman", label: "Gala dinners" },
      { href: "/services/omani-folk-performance", label: "Omani folk performance" },
      { href: "/services/event-production-oman", label: "Event production" },
    ],
    relatedIndustries: [
      { href: "/industries/sports-entertainment", label: "Sports & entertainment" },
      { href: "/industries/hospitality-tourism", label: "Hospitality & tourism" },
    ],
    relatedLocations: [muscat, salalah],
  },
  {
    slug: "cultural-festivals-oman",
    nav: "Festivals & Cultural Programmes",
    group: "cultural",
    title: "Festival and Cultural Programme Production in Oman",
    h1: "Festival overlays and cultural programmes with an operations clock",
    description:
      "Festival and cultural programme production in Oman, including seasonal overlays, public-facing hospitality and Khareef-adjacent gatherings planned with permissions, crowd flow and weather.",
    lede: "A festival is still an event operation: gates, shade, power, bilingual information and a plan for when the weather turns. We produce the overlay the host can actually run.",
    overview: [
      "Oman hosts seasonal and cultural gatherings that are not hotel conferences — Khareef-adjacent programmes in Salalah, National Day-related public evenings, heritage weekends and tourism overlays. The work is crowd maths, municipal coordination and a guest journey that does not collapse at peak.",
      "We do not claim official contracts or festival ownership. When a host, venue or organiser briefs us, we plan staging, hospitality, staffing and technical as one document. Indoor fallback is mandatory for outdoor looks.",
    ],
    includes: ["Site plan and crowd flow", "Permissions liaison", "Staging and power", "Staffing and guest information", "Weather fallback", "Show calling for timed features"],
    capabilities: ["Seasonal overlays", "Cultural evenings", "Tourism programmes", "Private festival-adjacent hospitality"],
    formats: ["Public-facing overlays", "Ticketed cultural nights", "Hosted seasonal receptions"],
    oman: [
      "Khareef humidity, Muscat heat and official-period diaries are production constraints. We will not promise a weather-proof outdoor spectacular.",
    ],
    approach: ["Recce the site. Write the permissions. Size the crew to peak, not to the moodboard."],
    audience: "Tourism hosts, cultural organisers, hotels and corporates attaching a seasonal or public chapter to a programme.",
    faqs: [
      {
        q: "Do you organise Oman’s public festivals?",
        a: "We produce overlays and programmes we are briefed to deliver. We do not claim to run national festivals or hold exclusive public contracts.",
      },
      {
        q: "Can you work during Khareef in Salalah?",
        a: "Yes, with earlier holds, moisture-aware kit and an indoor twin for every outdoor cue.",
      },
      {
        q: "Is this suitable for a private corporate group?",
        a: "Yes. Many briefs are hosted evenings that borrow festival energy without opening the gates to the public.",
      },
    ],
    relatedServices: [
      { href: "/services/dhofar-cultural-programming", label: "Dhofar programming" },
      { href: "/services/destination-events-oman", label: "Destination events" },
      { href: "/services/event-staffing-oman", label: "Event staffing" },
    ],
    relatedIndustries: [
      { href: "/industries/hospitality-tourism", label: "Hospitality & tourism" },
      { href: "/industries/government-public-sector", label: "Government" },
    ],
    relatedLocations: [muscat, salalah],
  },
];

export const serviceHubs = [
  { slug: "event-management", title: "Event Management", intro: "Planning, producing and show-calling programmes across Oman from a Muscat centre.", slugs: ["event-management-oman", "event-planning-oman", "corporate-events-oman", "conference-management-oman", "government-events-oman"] },
  { slug: "exhibitions", title: "Exhibitions", intro: "Hall operations, stand design and construction for Oman exhibition floors.", slugs: ["exhibition-management-oman", "exhibition-stand-design-oman", "exhibition-stand-construction-oman"] },
  { slug: "production", title: "Production", intro: "Stage, LED, lighting, sound and the crew who run them.", slugs: ["event-production-oman", "audio-visual-oman", "stage-design-oman", "lighting-sound-oman", "led-screens-oman"] },
  { slug: "branding", title: "Branding", intro: "Guest-facing surfaces and wayfinding as one bilingual system.", slugs: ["event-branding-oman", "event-signage-oman"] },
  { slug: "hospitality-staffing", title: "Hospitality & Staffing", intro: "People and arrival systems that make the programme feel considered.", slugs: ["event-staffing-oman", "registration-guest-management-oman", "gala-dinners-oman", "weddings-oman"] },
  { slug: "experiences", title: "Experiences", intro: "Launches, activations, roadshows and destination chapters with a caller on comms.", slugs: ["product-launches-oman", "brand-activations-oman", "roadshows-oman", "destination-events-oman", "vip-luxury-events-oman", "award-ceremonies-oman", "live-entertainment-oman"] },
  { slug: "cultural-hospitality", title: "Cultural Hospitality", intro: "Omani welcome rituals and performance, sourced with respect.", slugs: ["traditional-omani-hospitality", "omani-majlis-experiences", "frankincense-welcome-rituals", "omani-folk-performance", "dhofar-cultural-programming", "cultural-festivals-oman"] },
];

export function getService(slug: string) {
  return services.find((item) => item.slug === slug);
}

export function getHub(slug: string) {
  return serviceHubs.find((item) => item.slug === slug);
}
